exports.seed = function(knex) {
    return knex('states').insert([
        {id:1 , state_name:"Alabama"},
        {id:2 , state_name:"Alaska"},
        {id:3 , state_name:"Arizona"},
        {id:4 , state_name:"Arkansas"},
        {id:5 , state_name:"California"},
        {id:6 , state_name:"Colorado"},
        {id:7 , state_name:"Connecticut"},
        {id:8 , state_name:"Delaware"},
        {id:9 , state_name:"District of Columbia"},
        {id:10 , state_name:"Florida"},
        {id:11 , state_name:"Georgia"},
        {id:12 , state_name:"Hawaii"},
        {id:13 , state_name:"Idaho"},
        {id:14 , state_name:"Illinois"},
        {id:15 , state_name:"Indiana"},
        {id:16 , state_name:"Iowa"},
        {id:17 , state_name:"Kansas"},
        {id:18 , state_name:"Kentucky"},
        {id:19 , state_name:"Louisiana"},
        {id:20 , state_name:"Maine"},
        {id:21 , state_name:"Maryland"},
        {id:22 , state_name:"Massachusetts"},
        {id:23 , state_name:"Michigan"},
        {id:24 , state_name:"Minnesota"},
        {id:25 , state_name:"Mississippi"},
        {id:26 , state_name:"Missouri"},
        {id:27 , state_name:"Montana"},
        {id:28 , state_name:"Nebraska"},
        {id:29 , state_name:"Nevada"},
        {id:30 , state_name:"New Hampshire"},
        {id:31 , state_name:"New Jersey"},
        {id:32 , state_name:"New Mexico"},
        {id:33 , state_name:"New York"},
        {id:34 , state_name:"North Carolina"},
        {id:35 , state_name:"North Dakota"},
        {id:36 , state_name:"Ohio"},
        {id:37 , state_name:"Oklahoma"},
        {id:38 , state_name:"Oregon"},
        {id:39 , state_name:"Pennsylvania"},
        {id:40 , state_name:"Rhode Island"},
        {id:41 , state_name:"South Carolina"},
        {id:42 , state_name:"South Dakota"},
        {id:43 , state_name:"Tennessee"},
        {id:44 , state_name:"Texas"},
        {id:45 , state_name:"Utah"},
        {id:46 , state_name:"Vermont"},
        {id:47 , state_name:"Virginia"},
        {id:48 , state_name:"Washington"},
        {id:49 , state_name:"West Virginia"},
        {id:50 , state_name:"Wisconsin"},
        {id:51 , state_name:"Wyoming"}
    ]);
  };